'use client';

import { useState } from "react";
import Sidebar from "../Sidebar";
import Header from "@/components/Header";

export default function ClientBillingPage() {
  const invoices = [
    { id: 'INV-001', date: 'May 1, 2026', amount: '$1,200.00', status: 'Paid' },
    { id: 'INV-002', date: 'Apr 1, 2026', amount: '$1,200.00', status: 'Paid' },
    { id: 'INV-003', date: 'Mar 1, 2026', amount: '$950.00', status: 'Paid' },
  ];

  const [showCardModal, setShowCardModal] = useState(false);
  const [cardData, setCardData] = useState({
    cardNumber: '',
    expiry: '',
    cvv: '',
    cardName: ''
  });
  const [cardSaving, setCardSaving] = useState(false);

  const downloadInvoicePDF = async (
    invoiceNumber: string, 
    amount: string, 
    date: string
  ) => {
    try {
      const token = localStorage.getItem('token');
      const response = await fetch(
        `/api/client/billing/invoice/${invoiceNumber}/pdf`,
        {
          headers: {
            'Authorization': `Bearer ${token}`
          }
        }
      );

      if (response.ok) {
        const blob = await response.blob();
        const url = window.URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `${invoiceNumber}.pdf`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        window.URL.revokeObjectURL(url);
      } else {
        throw new Error('API not ready');
      }
    } catch (error) {
      const printWindow = window.open('', '_blank');
      if (printWindow) {
        printWindow.document.write(`
          <html>
          <head>
            <title>${invoiceNumber}</title>
            <style>
              body { font-family: Arial, sans-serif; 
                padding: 40px; color: #333; }
              .header { border-bottom: 2px solid #4f46e5; 
                padding-bottom: 20px; margin-bottom: 30px; }
              .title { font-size: 28px; color: #4f46e5; 
                font-weight: bold; }
              .row { display: flex; 
                justify-content: space-between; 
                padding: 10px 0; 
                border-bottom: 1px solid #eee; }
              .total { font-size: 20px; font-weight: bold; 
                color: #4f46e5; margin-top: 20px; }
              .footer { margin-top: 40px; 
                text-align: center; 
                color: #9ca3af; font-size: 12px; }
              .paid { background: #d1fae5; color: #065f46;
                padding: 4px 12px; border-radius: 20px;
                font-size: 12px; }
            </style>
          </head>
          <body>
            <div class="header">
              <div class="title">INVOICE</div>
              <div style="margin-top: 8px; 
                color: #6b7280;">
                Digital Marketing Hub
              </div>
            </div>
            <div class="row">
              <span style="color: #6b7280;">
                Invoice Number
              </span>
              <strong>${invoiceNumber}</strong>
            </div>
            <div class="row">
              <span style="color: #6b7280;">Date</span>
              <span>${date}</span>
            </div>
            <div class="row">
              <span style="color: #6b7280;">Plan</span>
              <span>Agency Pro Plan</span>
            </div>
            <div class="row">
              <span style="color: #6b7280;">Status</span>
              <span class="paid">Paid</span>
            </div>
            <div class="row total">
              <span>Total Amount</span>
              <span>${amount}</span>
            </div>
            <div class="footer">
              Generated by Digital Marketing Hub •
              Digital Agency Hub
            </div>
          </body>
          </html>
        `);
        printWindow.document.close();
        printWindow.print();
      }
    }
  };

  return (
    <div className="flex min-h-screen bg-slate-50">
      <Sidebar role="client" />
      <div className="flex-1 ml-[260px] flex flex-col">
        <Header />
        <main className="p-8 max-w-7xl mx-auto w-full">
          <div className="mb-10">
            <h1 className="text-2xl font-bold text-slate-900">Billing & Invoices</h1>
            <p className="text-sm text-slate-500 mt-1">Manage your payment methods and view history.</p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 mb-10">
            <div className="bg-white p-8 rounded-3xl border border-slate-200 shadow-sm lg:col-span-2">
              <h3 className="text-lg font-bold text-slate-900 mb-6">Active Subscription</h3>
              <div className="flex items-center justify-between p-6 bg-indigo-50 rounded-2xl border border-indigo-100">
                <div className="flex items-center gap-4">
                  <div className="w-12 h-12 bg-indigo-600 rounded-xl flex items-center justify-center text-white font-bold">
                    ★
                  </div>
                  <div>
                    <h4 className="font-bold text-slate-900">Agency Pro Plan</h4>
                    <p className="text-xs text-indigo-600 font-bold">Next billing: June 1, 2026</p>
                  </div>
                </div>
                <div className="text-right">
                  <div className="text-2xl font-bold text-slate-900">$1,200</div>
                  <div className="text-[10px] text-slate-500 uppercase font-black">per month</div>
                </div>
              </div>
            </div>

            <div className="bg-white p-8 rounded-3xl border border-slate-200 shadow-sm">
              <h3 className="text-lg font-bold text-slate-900 mb-6">Payment Method</h3>
              <div className="flex items-center gap-4 mb-6">
                <div className="w-12 h-8 bg-slate-100 rounded border border-slate-200 flex items-center justify-center font-bold text-[10px]">VISA</div>
                <div>
                  <div className="text-sm font-bold text-slate-900">•••• 4242</div>
                  <div className="text-[10px] text-slate-500 uppercase font-black">Expires 12/28</div>
                </div>
              </div>
              <button 
                onClick={() => setShowCardModal(true)}
                className="w-full py-2.5 text-xs font-bold text-indigo-600 border border-indigo-100 rounded-xl hover:bg-indigo-50 transition-colors"
              >
                Update Card
              </button>
            </div>
          </div>

          <div className="bg-white rounded-3xl border border-slate-200 shadow-sm overflow-hidden">
            <div className="p-6 border-b border-slate-100 bg-slate-50/50">
              <h3 className="text-base font-bold text-slate-900">Billing History</h3>
            </div>
            <div className="overflow-x-auto">
              <table className="w-full text-left">
                <thead>
                  <tr className="bg-slate-50 text-[10px] font-black text-slate-500 uppercase tracking-widest border-b border-slate-100">
                    <th className="px-8 py-4">Invoice ID</th>
                    <th className="px-8 py-4">Date</th>
                    <th className="px-8 py-4">Amount</th>
                    <th className="px-8 py-4">Status</th>
                    <th className="px-8 py-4 text-right">Action</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-50">
                  {invoices.map((inv) => (
                    <tr key={inv.id} className="hover:bg-slate-50 transition-colors group">
                      <td className="px-8 py-5 font-bold text-sm text-slate-900">{inv.id}</td>
                      <td className="px-8 py-5 text-sm text-slate-500">{inv.date}</td>
                      <td className="px-8 py-5 text-sm font-bold text-slate-900">{inv.amount}</td>
                      <td className="px-8 py-5">
                        <span className="px-2 py-0.5 rounded-full bg-green-50 text-green-600 text-[10px] font-bold border border-green-100">
                          {inv.status}
                        </span>
                      </td>
                      <td className="px-8 py-5 text-right">
                        <button 
                          onClick={() => downloadInvoicePDF(inv.id, inv.amount, inv.date)}
                          className="text-indigo-600 hover:underline font-bold text-xs"
                        >
                          PDF
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </main>
      </div>

      {showCardModal && (
        <div style={{
          position: 'fixed', top: 0, left: 0,
          right: 0, bottom: 0,
          background: 'rgba(0,0,0,0.5)',
          display: 'flex', alignItems: 'center',
          justifyContent: 'center', zIndex: 1000
        }} onClick={() => setShowCardModal(false)}>
          <div style={{
            background: 'white', borderRadius: '12px',
            padding: '24px', width: '400px',
            maxWidth: '90vw'
          }} onClick={e => e.stopPropagation()}>
            <h2 style={{ margin: '0 0 20px', fontSize: '18px' }}>
              Update Payment Method
            </h2>
            
            <div style={{ marginBottom: '16px' }}>
              <label style={{ fontSize: '13px', 
                color: '#6b7280', display: 'block',
                marginBottom: '6px' }}>
                Cardholder Name
              </label>
              <input
                type="text"
                placeholder="John Smith"
                value={cardData.cardName}
                onChange={e => setCardData({
                  ...cardData, cardName: e.target.value
                })}
                style={{ width: '100%', padding: '10px 12px',
                  border: '1px solid #e5e7eb',
                  borderRadius: '8px', fontSize: '14px',
                  boxSizing: 'border-box' }}
              />
            </div>

            <div style={{ marginBottom: '16px' }}>
              <label style={{ fontSize: '13px',
                color: '#6b7280', display: 'block',
                marginBottom: '6px' }}>
                Card Number
              </label>
              <input
                type="text"
                placeholder="•••• •••• •••• ••••"
                maxLength={19}
                value={cardData.cardNumber}
                onChange={e => {
                  let val = e.target.value
                    .replace(/\D/g, '')
                    .replace(/(.{4})/g, '$1 ')
                    .trim();
                  setCardData({ ...cardData, cardNumber: val });
                }}
                style={{ width: '100%', padding: '10px 12px',
                  border: '1px solid #e5e7eb',
                  borderRadius: '8px', fontSize: '14px',
                  boxSizing: 'border-box' }}
              />
            </div>

            <div style={{ display: 'flex', gap: '12px',
              marginBottom: '24px' }}>
              <div style={{ flex: 1 }}>
                <label style={{ fontSize: '13px',
                  color: '#6b7280', display: 'block',
                  marginBottom: '6px' }}>
                  Expiry (MM/YY)
                </label>
                <input
                  type="text"
                  placeholder="MM/YY"
                  maxLength={5}
                  value={cardData.expiry}
                  onChange={e => {
                    let val = e.target.value
                      .replace(/\D/g, '')
                      .replace(/^(\d{2})(\d)/, '$1/$2');
                    setCardData({ ...cardData, expiry: val });
                  }}
                  style={{ width: '100%', padding: '10px 12px',
                    border: '1px solid #e5e7eb',
                    borderRadius: '8px', fontSize: '14px',
                    boxSizing: 'border-box' }}
                />
              </div>
              <div style={{ flex: 1 }}>
                <label style={{ fontSize: '13px',
                  color: '#6b7280', display: 'block',
                  marginBottom: '6px' }}>
                  CVV
                </label>
                <input
                  type="password"
                  placeholder="•••"
                  maxLength={4}
                  value={cardData.cvv}
                  onChange={e => setCardData({
                    ...cardData,
                    cvv: e.target.value.replace(/\D/g, '')
                  })}
                  style={{ width: '100%', padding: '10px 12px',
                    border: '1px solid #e5e7eb',
                    borderRadius: '8px', fontSize: '14px',
                    boxSizing: 'border-box' }}
                />
              </div>
            </div>

            <div style={{ display: 'flex', gap: '12px' }}>
              <button
                onClick={() => setShowCardModal(false)}
                style={{ flex: 1, padding: '10px',
                  border: '1px solid #e5e7eb',
                  borderRadius: '8px', background: 'white',
                  cursor: 'pointer', fontSize: '14px' }}>
                Cancel
              </button>
              <button
                onClick={async () => {
                  if (!cardData.cardNumber || 
                      !cardData.expiry || 
                      !cardData.cvv ||
                      !cardData.cardName) {
                    alert('Please fill all fields');
                    return;
                  }
                  setCardSaving(true);
                  await new Promise(r => setTimeout(r, 1000));
                  setCardSaving(false);
                  setShowCardModal(false);
                  alert('Payment method updated successfully!');
                }}
                disabled={cardSaving}
                style={{ flex: 1, padding: '10px',
                  background: '#4f46e5', color: 'white',
                  border: 'none', borderRadius: '8px',
                  cursor: 'pointer', fontSize: '14px',
                  fontWeight: '500' }}>
                {cardSaving ? 'Saving...' : 'Save Card'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
