import { Response } from 'express';
import { db } from '../db';
import { campaigns, clients, tenantBranding } from '../db/schema';
import { eq, and, sql } from 'drizzle-orm';
import { AuthRequest } from '../middleware/authMiddleware';
import PDFDocument from 'pdfkit';

/**
 * GET /api/reports/export
 */
export const exportReport = async (req: AuthRequest, res: Response) => {
  try {
    const tenantId = req.user.tenantId;
    const { format, clientId } = req.query;

    let whereClause = eq(campaigns.tenantId, tenantId);
    
    if (clientId) {
      whereClause = and(whereClause, eq(campaigns.clientId, clientId as string)) as any;
    }

    const data = await db.select().from(campaigns).where(whereClause);

    if (format === 'csv') {
      const headers = ['ID', 'Name', 'Channel', 'Budget', 'Impressions', 'Clicks', 'Conversions', 'Spend', 'Status'];
      const rows = data.map(c => [
        c.id, 
        `"${c.name}"`, 
        c.channel, 
        c.budget, 
        c.impressions, 
        c.clicks, 
        c.conversions, 
        c.spend, 
        c.status
      ].join(','));
      
      const csvContent = [headers.join(','), ...rows].join('\n');
      
      res.setHeader('Content-Type', 'text/csv');
      res.setHeader('Content-Disposition', `attachment; filename=report-${Date.now()}.csv`);
      return res.send(csvContent);
    }

    if (format === 'json') {
      res.setHeader('Content-Type', 'application/json');
      res.setHeader('Content-Disposition', `attachment; filename=report-${Date.now()}.json`);
      return res.json(data);
    }

    res.json({ message: 'Requested format not yet implemented. Try format=csv or format=json' });
  } catch (error) {
    console.error('[REPORT_EXPORT_ERROR]', error);
    res.status(500).json({ message: 'Error generating report' });
  }
};

/**
 * GET /api/client/report/pdf
 */
export const exportClientPDF = async (req: AuthRequest, res: Response) => {
  try {
    const tenantId = req.user.tenantId;
    
    // 1. Fetch Data
    const [branding] = await db.select().from(tenantBranding).where(eq(tenantBranding.tenantId, tenantId)).limit(1);
    const data = await db.select().from(campaigns).where(eq(campaigns.tenantId, tenantId));
    
    // 2. Calculate Totals
    const totals = data.reduce((acc, c) => ({
      spend: acc.spend + (c.spend || 0),
      impressions: acc.impressions + (c.impressions || 0),
      clicks: acc.clicks + (c.clicks || 0),
      conversions: acc.conversions + (c.conversions || 0)
    }), { spend: 0, impressions: 0, clicks: 0, conversions: 0 });

    // 3. Generate PDF
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=campaign-report-${Date.now()}.pdf`);
    
    doc.pipe(res);

    // HEADER
    doc.fontSize(24).font('Helvetica-Bold').fillColor(branding?.primaryColor || '#4f46e5').text('Campaign Performance Report', { align: 'center' });
    doc.moveDown(0.2);
    doc.fontSize(10).font('Helvetica').fillColor('#64748b').text(`Generated on ${new Date().toLocaleDateString()} for Agency ID: ${tenantId}`, { align: 'center' });
    doc.moveDown(2);

    // STATS GRID
    doc.rect(50, doc.y, 500, 80).fill('#f8fafc');
    doc.fillColor('#1e293b');
    
    const startY = doc.y + 20;
    doc.fontSize(10).font('Helvetica-Bold').text('TOTAL SPEND', 70, startY);
    doc.fontSize(18).text(`$${totals.spend.toLocaleString()}`, 70, startY + 15);

    doc.fontSize(10).text('IMPRESSIONS', 200, startY);
    doc.fontSize(18).text(totals.impressions.toLocaleString(), 200, startY + 15);

    doc.fontSize(10).text('CLICKS', 330, startY);
    doc.fontSize(18).text(totals.clicks.toLocaleString(), 330, startY + 15);

    doc.fontSize(10).text('CONVERSIONS', 460, startY);
    doc.fontSize(18).text(totals.conversions.toLocaleString(), 460, startY + 15);

    doc.moveDown(6);

    // TABLE HEADER
    doc.fontSize(14).font('Helvetica-Bold').fillColor('#0f172a').text('Active Campaigns Breakdown');
    doc.moveDown(1);

    const tableTop = doc.y;
    doc.fontSize(10).fillColor('#64748b');
    doc.text('Campaign Name', 50, tableTop);
    doc.text('Status', 300, tableTop);
    doc.text('Budget', 450, tableTop);
    
    doc.moveTo(50, tableTop + 15).lineTo(550, tableTop + 15).strokeColor('#e2e8f0').stroke();

    // TABLE ROWS
    let currentY = tableTop + 25;
    doc.fillColor('#334155').font('Helvetica');

    data.forEach(c => {
      if (currentY > 750) { doc.addPage(); currentY = 50; }
      doc.text(c.name, 50, currentY);
      doc.text(c.status?.toUpperCase() || 'ACTIVE', 300, currentY);
      doc.text(`$${c.budget?.toLocaleString()}`, 450, currentY);
      currentY += 25;
    });

    // FOOTER
    doc.fontSize(10).fillColor('#94a3b8').text('Generated by Digital Marketing Hub', 50, 780, { align: 'center' });

    doc.end();

  } catch (error) {
    console.error('[PDF_EXPORT_ERROR]', error);
    res.status(500).json({ message: 'Error generating PDF report' });
  }
};

/**
 * GET /api/client/campaigns/:campaignId/pdf
 */
export const exportSingleCampaignPDF = async (req: AuthRequest, res: Response) => {
  try {
    const tenantId = req.user.tenantId;
    const { campaignId } = req.params;

    // 1. Fetch Campaign and Verify Ownership
    const [campaign] = await db.select().from(campaigns)
      .where(and(eq(campaigns.id, campaignId), eq(campaigns.tenantId, tenantId)))
      .limit(1);

    if (!campaign) {
      return res.status(404).json({ message: 'Campaign not found or unauthorized' });
    }

    const [branding] = await db.select().from(tenantBranding).where(eq(tenantBranding.tenantId, tenantId)).limit(1);

    // 2. Generate PDF
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=${campaign.name.replace(/\s+/g, '-')}-report.pdf`);
    
    doc.pipe(res);

    // HEADER
    doc.fontSize(24).font('Helvetica-Bold').fillColor(branding?.primaryColor || '#4f46e5').text('Campaign Report', { align: 'center' });
    doc.moveDown(0.2);
    doc.fontSize(16).font('Helvetica').fillColor('#1e293b').text(campaign.name, { align: 'center' });
    doc.moveDown(0.5);
    doc.fontSize(10).font('Helvetica').fillColor('#64748b').text(`Generated on ${new Date().toLocaleDateString()}`, { align: 'center' });
    doc.moveDown(2);

    // DETAILS
    doc.rect(50, doc.y, 500, 100).fill('#f8fafc');
    doc.fillColor('#1e293b');
    
    const startY = doc.y + 20;
    
    doc.fontSize(10).font('Helvetica-Bold').text('STATUS', 70, startY);
    doc.fontSize(14).font('Helvetica').text(campaign.status?.toUpperCase() || 'UNKNOWN', 70, startY + 15);

    doc.fontSize(10).font('Helvetica-Bold').text('BUDGET', 200, startY);
    doc.fontSize(14).font('Helvetica').text(`$${(campaign.budget || 0).toLocaleString()}`, 200, startY + 15);

    doc.fontSize(10).font('Helvetica-Bold').text('SPEND', 330, startY);
    doc.fontSize(14).font('Helvetica').text(`$${(campaign.spend || 0).toLocaleString()}`, 330, startY + 15);

    // PERFORMANCE METRICS
    doc.moveDown(6);
    doc.fontSize(16).font('Helvetica-Bold').fillColor('#0f172a').text('Performance Metrics');
    doc.moveDown(1);

    doc.fontSize(12).font('Helvetica').fillColor('#334155');
    doc.text(`Impressions: ${(campaign.impressions || 0).toLocaleString()}`);
    doc.moveDown(0.5);
    doc.text(`Clicks: ${(campaign.clicks || 0).toLocaleString()}`);
    doc.moveDown(0.5);
    doc.text(`Conversions: ${(campaign.conversions || 0).toLocaleString()}`);
    doc.moveDown(0.5);
    
    const roas = campaign.spend ? ((campaign.conversions || 0) * 50 / campaign.spend).toFixed(2) : '0.00'; // Mock ROAS calculation
    doc.text(`Estimated ROAS: ${roas}x`);

    // FOOTER
    doc.fontSize(10).fillColor('#94a3b8').text('Generated by Digital Marketing Hub', 50, 780, { align: 'center' });

    doc.end();

  } catch (error) {
    console.error('[SINGLE_PDF_EXPORT_ERROR]', error);
    res.status(500).json({ message: 'Error generating PDF report' });
  }
};

