export const PLANS = {
  starter: {
    id:          'starter',
    name:        'Starter',
    price:       49,
    annualPrice: 490, // 2 months free
    currency:    'USD',
    color:       '#6366F1',
    icon:        '🚀',
    description: 'Perfect for solo operators and small agencies',
    stripePriceIdMonthly: process.env.STRIPE_PRICE_STARTER_MONTHLY || '',
    stripePriceIdAnnual: process.env.STRIPE_PRICE_STARTER_ANNUAL || '',
    limits: {
      clientWorkspaces:   3,
      teamSeats:          2,
      socialPostsPerMonth:200,
      bioPages:           1,
      shortLinksPerMonth: 500,
      automationWorkflows:5,
      channelsConnected:  2,
    },
    features: [
      { label:'3 Client Workspaces', included:true },
      { label:'2 Team Seats', included:true },
      { label:'Campaign Management', included:true },
      { label:'2 Channels Connected', included:true },
      { label:'200 Social Posts/month', included:true },
      { label:'1 Bio Page', included:true },
      { label:'500 Short Links/month', included:true },
      { label:'Static QR Codes', included:true },
      { label:'Basic Attribution', included:true },
      { label:'5 Automation Workflows', included:true },
      { label:'Email Support', included:true },
      { label:'White-Label Branding', included:false },
      { label:'AI Creative Automation', included:false },
      { label:'Instagram DM Automation', included:false },
      { label:'SEO + Content Analysis', included:false },
      { label:'CRM + Lead Scoring', included:false },
    ],
  },
  growth: {
    id:          'growth',
    name:        'Growth',
    price:       149,
    annualPrice: 1490,
    currency:    'USD',
    color:       '#8B5CF6',
    icon:        '📈',
    description: 'For growing agencies managing multiple clients',
    stripePriceIdMonthly: process.env.STRIPE_PRICE_GROWTH_MONTHLY || '',
    stripePriceIdAnnual: process.env.STRIPE_PRICE_GROWTH_ANNUAL || '',
    badge:       'Most Popular',
    limits: {
      clientWorkspaces:    10,
      teamSeats:           5,
      socialPostsPerMonth: 1000,
      bioPages:            10,
      shortLinksPerMonth:  5000,
      automationWorkflows: 25,
      channelsConnected:   5,
    },
    features: [
      { label:'10 Client Workspaces', included:true },
      { label:'5 Team Seats', included:true },
      { label:'White-Label Branding', included:true },
      { label:'5 Channels Connected', included:true },
      { label:'1,000 Social Posts/month',included:true },
      { label:'10 Bio Pages', included:true },
      { label:'5,000 Short Links/month', included:true },
      { label:'Dynamic QR Codes', included:true },
      { label:'Advanced Attribution', included:true },
      { label:'A/B Testing', included:true },
      { label:'25 Automation Workflows', included:true },
      { label:'Limited AI Creative', included:true },
      { label:'SEO + Content Analysis', included:true },
      { label:'CRM + Lead Scoring', included:true },
      { label:'Email + Chat Support', included:true },
      { label:'2 months free (annual)',included:true },
      { label:'Instagram DM Automation',included:false },
      { label:'Custom Domain', included:false },
      { label:'Server-Side Tracking', included:false },
    ],
  },
  agency_pro: {
    id:          'agency_pro',
    name:        'Agency Pro',
    price:       349,
    annualPrice: 3490,
    currency:    'USD',
    color:       '#F59E0B',
    icon:        '⚡',
    description: 'For established agencies with unlimited needs',
    stripePriceIdMonthly: process.env.STRIPE_PRICE_AGENCY_MONTHLY || '',
    stripePriceIdAnnual: process.env.STRIPE_PRICE_AGENCY_ANNUAL || '',
    badge:       'Best Value',
    limits: {
      clientWorkspaces:    -1, // unlimited
      teamSeats:           15,
      socialPostsPerMonth: -1, // unlimited
      bioPages:            -1, // unlimited
      shortLinksPerMonth:  -1, // unlimited
      automationWorkflows: -1, // unlimited
      channelsConnected:   -1, // unlimited
    },
    features: [
      { label:'Unlimited Client Workspaces', included:true },
      { label:'15 Team Seats', included:true },
      { label:'White-Label Branding', included:true },
      { label:'Custom Domain', included:true },
      { label:'All Channels', included:true },
      { label:'Unlimited Everything', included:true },
      { label:'Full AI Creative', included:true },
      { label:'Instagram DM Automation',included:true },
      { label:'Server-Side Tracking', included:true },
      { label:'Social Listening', included:true },
      { label:'AI Visibility Tracking', included:true },
      { label:'SSO (Google/Microsoft)', included:true },
      { label:'Dedicated CSM', included:true },
      { label:'Read API Access', included:true },
      { label:'2 months free (annual)', included:true },
      { label:'Predictive Analytics', included:false },
      { label:'24/7 SLA Support', included:false },
    ],
  },
  enterprise: {
    id:          'enterprise',
    name:        'Enterprise',
    price:       0, // custom
    annualPrice: 0,
    currency:    'USD',
    color:       '#10B981',
    icon:        '🏢',
    description: 'Custom solutions for large agencies and enterprises',
    stripePriceIdMonthly: '',
    stripePriceIdAnnual: '',
    limits: {
      clientWorkspaces:    -1,
      teamSeats:           -1,
      socialPostsPerMonth: -1,
      bioPages:            -1,
      shortLinksPerMonth:  -1,
      automationWorkflows: -1,
      channelsConnected:   -1,
    },
    features: [
      { label:'Everything in Agency Pro', included:true },
      { label:'Unlimited Team Seats', included:true },
      { label:'Predictive Analytics', included:true },
      { label:'Full API Access', included:true },
      { label:'24/7 SLA Support', included:true },
      { label:'Custom Integrations', included:true },
      { label:'Dedicated Account Manager',included:true },
      { label:'Custom Onboarding',      included:true },
      { label:'SLA Guarantees',         included:true },
      { label:'Negotiated Annual Pricing',included:true },
    ],
  },
} as const;

export type PlanId = keyof typeof PLANS;
