'use client';

import { useState } from 'react';

export default function ClientReports() {
  const [showRequestModal, setShowRequestModal] = 
    useState<boolean>(false);
  const [reportType, setReportType] = 
    useState<string>('Campaign Performance');
  const [notes, setNotes] = 
    useState<string>('');
  const [requesting, setRequesting] = 
    useState<boolean>(false);

  const reports = [
    {
      id: '1',
      title: 'Monthly Performance - April 2026',
      date: '2026-05-01',
      size: '2.4 MB',
      invoiceNumber: 'RPT-001',
      amount: 0
    },
    {
      id: '2',
      title: 'Quarterly Review Q1',
      date: '2026-04-05',
      size: '5.1 MB',
      invoiceNumber: 'RPT-002',
      amount: 0
    },
    {
      id: '3',
      title: 'Ad Spend Breakdown',
      date: '2026-03-28',
      size: '1.2 MB',
      invoiceNumber: 'RPT-003',
      amount: 0
    }
  ];

  const downloadReport = (title: string) => {
    const win = window.open('', '_blank');
    if (win) {
      win.document.write(`
        <html><head>
          <title>${title}</title>
          <style>
            body { font-family: Arial;
              padding: 40px; }
            h1 { color: #4f46e5; }
            .section { margin: 20px 0; }
            .row { display: flex;
              justify-content: space-between;
              padding: 10px 0;
              border-bottom: 1px solid #eee; }
          </style>
        </head>
        <body>
          <h1>${title}</h1>
          <p style="color:#6b7280">
            Generated: ${new Date()
              .toLocaleDateString()}
          </p>
          <div class="section">
            <h2>Performance Summary</h2>
            <div class="row">
              <span>Total Spend</span>
              <strong>$4,500</strong>
            </div>
            <div class="row">
              <span>Impressions</span>
              <strong>1.2M</strong>
            </div>
            <div class="row">
              <span>Clicks</span>
              <strong>24.5K</strong>
            </div>
            <div class="row">
              <span>Conversions</span>
              <strong>482</strong>
            </div>
          </div>
          <p style="color:#9ca3af;
            text-align:center;
            margin-top:40px">
            Generated by Digital Marketing Hub
          </p>
        </body></html>
      `);
      win.document.close();
      win.print();
    }
  };

  const handleRequestReport = async () => {
    setRequesting(true);
    await new Promise(r => 
      setTimeout(r, 1000));
    setRequesting(false);
    setShowRequestModal(false);
    setNotes('');
    alert(
      'Report requested! Your agency will ' +
      'generate it within 24 hours.'
    );
  };

  return (
    <div style={{
      padding: '32px',
      background: '#f9fafb',
      minHeight: '100vh'
    }}>
      <div style={{
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: '24px'
      }}>
        <div>
          <h1 style={{
            fontSize: '26px',
            fontWeight: '700',
            margin: '0 0 8px',
            color: '#111827'
          }}>
            Campaign Reports
          </h1>
          <p style={{
            color: '#6b7280',
            margin: 0,
            fontSize: '14px'
          }}>
            Download and analyze your 
            agency performance reports.
          </p>
        </div>
        <button
          onClick={() =>
            setShowRequestModal(true)}
          style={{
            padding: '10px 20px',
            background: '#4f46e5',
            color: 'white',
            border: 'none',
            borderRadius: '8px',
            cursor: 'pointer',
            fontWeight: '500',
            fontSize: '14px'
          }}
        >
          Request Custom Report
        </button>
      </div>

      <div style={{
        display: 'flex',
        flexDirection: 'column',
        gap: '12px'
      }}>
        {reports.map(report => (
          <div
            key={report.id}
            style={{
              background: 'white',
              borderRadius: '12px',
              border: '1px solid #e5e7eb',
              padding: '20px 24px',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between'
            }}
          >
            <div style={{
              display: 'flex',
              alignItems: 'center',
              gap: '16px'
            }}>
              <div style={{
                background: '#fee2e2',
                color: '#dc2626',
                padding: '8px 12px',
                borderRadius: '8px',
                fontWeight: '700',
                fontSize: '12px'
              }}>
                PDF
              </div>
              <div>
                <div style={{
                  fontWeight: '600',
                  color: '#111827',
                  marginBottom: '4px'
                }}>
                  {report.title}
                </div>
                <div style={{
                  fontSize: '13px',
                  color: '#6b7280'
                }}>
                  Generated on {report.date}
                  {' • '}{report.size}
                </div>
              </div>
            </div>
            <button
              onClick={() =>
                downloadReport(report.title)}
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: '6px',
                background: 'none',
                border: 'none',
                color: '#4f46e5',
                cursor: 'pointer',
                fontWeight: '500',
                fontSize: '14px'
              }}
            >
              ↓ Download
            </button>
          </div>
        ))}
      </div>

      {/* Request Modal */}
      {showRequestModal && (
        <div
          style={{
            position: 'fixed',
            top: 0, left: 0,
            right: 0, bottom: 0,
            background: 'rgba(0,0,0,0.5)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            zIndex: 1000
          }}
          onClick={() =>
            setShowRequestModal(false)}
        >
          <div
            style={{
              background: 'white',
              borderRadius: '12px',
              padding: '28px',
              width: '440px',
              maxWidth: '90vw'
            }}
            onClick={e =>
              e.stopPropagation()}
          >
            <h2 style={{
              margin: '0 0 20px',
              fontSize: '18px',
              fontWeight: '600'
            }}>
              Request Custom Report
            </h2>

            <div style={{
              marginBottom: '16px'
            }}>
              <label style={{
                display: 'block',
                fontSize: '13px',
                fontWeight: '500',
                marginBottom: '6px',
                color: '#374151'
              }}>
                Report Type
              </label>
              <select
                value={reportType}
                onChange={e =>
                  setReportType(
                    e.target.value
                  )}
                style={{
                  width: '100%',
                  padding: '10px 12px',
                  border: 
                    '1px solid #e5e7eb',
                  borderRadius: '8px',
                  fontSize: '14px',
                  background: 'white'
                }}
              >
                <option>
                  Campaign Performance
                </option>
                <option>
                  Ad Spend Analysis
                </option>
                <option>
                  Conversion Tracking
                </option>
                <option>
                  ROI Summary
                </option>
              </select>
            </div>

            <div style={{
              marginBottom: '24px'
            }}>
              <label style={{
                display: 'block',
                fontSize: '13px',
                fontWeight: '500',
                marginBottom: '6px',
                color: '#374151'
              }}>
                Additional Notes (optional)
              </label>
              <textarea
                value={notes}
                onChange={e =>
                  setNotes(e.target.value)}
                placeholder="Any specific requirements..."
                rows={3}
                style={{
                  width: '100%',
                  padding: '10px 12px',
                  border: 
                    '1px solid #e5e7eb',
                  borderRadius: '8px',
                  fontSize: '14px',
                  resize: 'none',
                  boxSizing: 'border-box'
                }}
              />
            </div>

            <div style={{
              display: 'flex',
              gap: '12px'
            }}>
              <button
                onClick={() =>
                  setShowRequestModal(
                    false
                  )}
                style={{
                  flex: 1,
                  padding: '11px',
                  border: 
                    '1px solid #e5e7eb',
                  borderRadius: '8px',
                  background: 'white',
                  cursor: 'pointer',
                  fontSize: '14px'
                }}
              >
                Cancel
              </button>
              <button
                onClick={
                  handleRequestReport
                }
                disabled={requesting}
                style={{
                  flex: 1,
                  padding: '11px',
                  background: requesting
                    ? '#9ca3af'
                    : '#4f46e5',
                  color: 'white',
                  border: 'none',
                  borderRadius: '8px',
                  cursor: requesting
                    ? 'not-allowed'
                    : 'pointer',
                  fontSize: '14px',
                  fontWeight: '500'
                }}
              >
                {requesting
                  ? 'Sending...'
                  : 'Send Request'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
